### ISSUE TITLE
I have created an extension for VSCode

### ISSUE THREAD

**Issue by vemel** [chrishollinworth/vscode-boto3-intellisense#2]
Hello!

Thank you for your efforts and support!

I have just released an extension that installs `boto3-stubs` for VSCode: https://marketplace.visualstudio.com/items?itemName=Boto3typed.boto3-ide

I would really appreciate it if you could try it out. Also, feel free to share your ideas.

Regards, Vlad.

**Comment by chrishollinworth** [comment]
Well done, I will be sure to check it out!
